version: '3.8'

services:
  app:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"
    container_name: my-app
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${IMAGE_TAG}