name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/react-app-repo:prod .

      - name: Push Image to Artifact Registry
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/react-app-repo:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure Docker authentication for Google Artifact Registry.
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Deploy via SSH
      - name: Deploy React App via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/gcp-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev
            sudo docker pull us-central1-docker.pkg.dev/optimum-agency-453414-m1/react-app-repo/react-app-repo:prod
            sudo docker stop react-app || true
            sudo docker rm react-app || true
            sudo docker run -d -p 80:80 --name react-app us-central1-docker.pkg.dev/optimum-agency-453414-m1/react-app-repo/react-app-repo:prod
            rm /tmp/gcp-key.json  # Clean up key file