name: Deploy React App

on:
  push:
    branches:
      - main  # Adjust this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud using the Service Account Key from GitHub Secrets
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure Docker to authenticate with Google Artifact Registry
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Pull the latest Docker image and deploy it on the VM
      - name: Deploy React App via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull us-central1-docker.pkg.dev/optimum-agency-453414-m1/react-app-repo/react-app-repo:prod
            sudo docker stop react-app || true
            sudo docker rm react-app || true
            sudo docker run -d -p 80:80 --name react-app us-central1-docker.pkg.dev/optimum-agency-453414-m1/react-app-repo/react-app-repo:prod
